# Generated by Django 5.0.6 on 2026-04-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('CI', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('NAME', models.CharField(max_length=20, verbose_name='Nombre')),
                ('SURNAME', models.CharField(max_length=20, verbose_name='Apellido')),
                ('DIRECTION', models.CharField(max_length=20, verbose_name='Direccion')),
                ('BIRTHDATE', models.DateField(verbose_name='Fecha_nacimiento')),
                ('USERNAME', models.CharField(max_length=20, verbose_name='Usuario')),
                ('PASSWORD', models.CharField(max_length=20, verbose_name='Clave')),
            ],
            options={
                'verbose_name': 'Cliente',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_PRODUCT', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Producto')),
                ('PRODUCT_NAME', models.CharField(max_length=20, verbose_name='Nombre_producto')),
                ('SIZE', models.CharField(max_length=20, verbose_name='Tamaño')),
                ('TYPE', models.CharField(max_length=20, verbose_name='Presentacion')),
                ('PRICE', models.CharField(max_length=20, verbose_name='Precio')),
                ('STOCK', models.IntegerField(max_length=20, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('ID_REQUEST', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Pedido')),
                ('DATE', models.DateField(max_length=20, verbose_name='Fecha_pedido')),
                ('TIME', models.TimeField(max_length=20, verbose_name='Etiqueta')),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('ID_DETAILS', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Pedido')),
                ('AMOUNT', models.CharField(max_length=20, verbose_name='Cantidad')),
                ('TOTAL', models.CharField(max_length=20, verbose_name='Monto_total')),
                ('ID_PEDIDO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.pedidos', verbose_name='Pedido')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.productos', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalles',
                'db_table': 'Detalles',
            },
        ),
    ]
