# Generated by Django 5.0.6 on 2026-04-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='TOTAL',
            field=models.IntegerField(max_length=20, verbose_name='Monto_total'),
        ),
    ]
