# Generated by Django 5.0.6 on 2026-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_detalles_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='TYPE',
            field=models.BooleanField(verbose_name='Presentacion'),
        ),
    ]
