# Generated by Django 5.0.6 on 2026-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_productos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='TOTAL',
            field=models.IntegerField(verbose_name='Monto_total'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='STOCK',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
