# Generated by Django 5.0.6 on 2026-04-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_productos_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_admin',
            fields=[
                ('ADMIN_CI', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('PASSWORD', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'administrador',
                'db_table': 'administrador',
            },
        ),
    ]
