# Generated by Django 5.0.6 on 2026-04-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_detalles_total_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='PASSWORD',
            field=models.CharField(max_length=128, verbose_name='Clave'),
        ),
    ]
