# Generated by Django 5.0.6 on 2026-04-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_user_admin'),
        ('APP', '0005_alter_clientes_password'),
    ]

    operations = [
    ]
