# Generated by Django 5.0.6 on 2026-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_merge_0004_user_admin_0005_alter_clientes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='PASSWORD',
            field=models.CharField(max_length=20, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='detalles',
            name='TOTAL',
            field=models.IntegerField(max_length=20, verbose_name='Monto_total'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='STOCK',
            field=models.IntegerField(max_length=20, verbose_name='Cantidad'),
        ),
    ]
